apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: my-app
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ./apps/my-app
      sourceRef:
        kind: GitRepository
        name: my-app
        namespace: flux-system
  values:
    replicaCount: 2
