apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: my-app
  namespace: flux-system
spec:
  interval: 2m
  url: https://github.com/SuyogWani/flux-drift-demo
  ref:
    branch: main